name: Deploy Images to GHCR

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - master
  workflow_dispatch:

jobs:
  build-push-image:
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            platform: linux/amd64
          - runner: ubuntu-24.04-arm
            platform: linux/arm64
    runs-on: ${{ matrix.runner }}
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build OCI Image"
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
          podman build . --platform ${{ matrix.platform}} -t ghcr.io/evanc577/sourcecatcher:latest
          podman push ghcr.io/evanc577/sourcecatcher:latest
